# Generated by Django 5.1 on 2024-10-19 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_requested', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=20)),
                ('units_donated', models.IntegerField()),
                ('last_donated', models.DateField(blank=True, null=True)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodtype')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
