# Generated by Django 5.1 on 2024-10-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bloodtype_bloodrequest_bloodinventory_blooddonor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='units_donated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtype',
            name='name',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3, unique=True),
        ),
    ]
