# Generated by Django 5.1 on 2024-10-19 06:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blooddonor_units_donated_alter_bloodtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='blood_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodtype', unique=True),
        ),
        migrations.AlterField(
            model_name='bloodinventory',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
