# Generated by Django 5.1 on 2024-10-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bloodinventory_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='donor_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
